name: r-environment
channels:
  - conda-forge
  - defaults
dependencies:
  - r-base=4.3
  - r-dplyr
  - r-naniar
  - r-plyr
  - r-mgcv
  - r-itsadug
  - r-sjplot
  - r-tidyverse
  - r-devtools
  - r-remotes
  - r-irkernel  # Required to run R code in a Jupyter notebook
  - pandoc
  - notebook
  - ipykernel
  - wget   # To allow downloading files via bash scripts (optional)
